# Generated by Django 4.1.5 on 2023-02-25 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='brand_photos/')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('men', 'MEN'), ('women', 'WOMEN'), ('kids', 'KIDS')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FootwearType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(choices=[('red', 'RED'), ('black', 'BLACK'), ('white', 'WHITE'), ('blue', 'BLUE'), ('brown', 'BROWN'), ('gray', 'GRAY')], max_length=50)),
                ('image', models.ImageField(upload_to='product_photos/')),
                ('size', models.CharField(choices=[('38', '38'), ('39', '39'), ('40', '40'), ('41', '41'), ('42', '42'), ('43', '43'), ('44', '44'), ('45', '45'), ('46', '46')], max_length=2)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('price', models.FloatField()),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_manager.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_manager.category')),
                ('footware_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_manager.footweartype')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
